#!/usr/bin/env python3
"""Builds packs/vintage-keyboard from the files fetch.sh downloaded.

    tools/pack-sources/vintage-keyboard/fetch.sh DOWNLOADS
    python3 tools/pack-sources/vintage-keyboard/build.py --downloads DOWNLOADS \\
        [--out packs/vintage-keyboard]

The five recordings are jim-ph's Freesound pack 12363, each CC0-1.0 (checked on each
Freesound page on 2026-10-02, see SOURCES.md). The script checks each download against the
size and git blob SHA-1 GitHub reported, and each WAV's length against its Freesound page,
which is how Tickeys' 1.wav … 5.wav are matched to the Freesound sounds.

Each recording is a whole keystroke: the key-down, then the key-up 120-170 ms later in the
same take. The build splits every take at the quietest point between the two strokes, so the
key-down plays on press and the take's own key-up on release.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np

sys.dont_write_bytecode = True  # keep the source tree clean of __pycache__
sys.path.insert(0, str(Path(__file__).resolve().parent))
import packlib as pl  # noqa: E402

PACK_ID = "vintage-keyboard"
CHECKED = "2026-10-02"
RATE = 44100
VARIATION = {"pitch": 0.02, "volume": 0.08}
CC0_URL = "https://creativecommons.org/publicdomain/zero/1.0/"
PACK_PAGE = "https://freesound.org/people/jim-ph/packs/12363/"
TICKEYS_COMMIT = "028083403ab75eae752446ce30cffb3b22b49eab"
TICKEYS_RAW = (f"https://raw.githubusercontent.com/yingDev/Tickeys/{TICKEYS_COMMIT}"
               "/Tickeys.app/Contents/Resources/data/mechanical/")
TICKEYS_TREE = (f"https://github.com/yingDev/Tickeys/tree/{TICKEYS_COMMIT}"
                "/Tickeys.app/Contents/Resources/data/mechanical")
REPO_ROOT = Path(__file__).resolve().parents[3]
MARKER = "<!-- generated by tools/pack-sources/vintage-keyboard/build.py -->"
MAX_SECONDS = 0.4
# Playback level, written to pack.json as "volume"; it changes no audio file. It matches the
# pack's typing loudness to TakTak's reference typing level (pl.REFERENCE_LK), so switching packs does
# not jump in volume. Measured on the built pack with
#     cargo run -p synth-packs --release -- loudness packs/vintage-keyboard
# (tools/synth-packs/src/loudness.rs): LK_AS_BUILT at volume 1.0. Recorded in SOURCES.md;
# re-measure whenever the processing here changes.
VOLUME = 0.88
LK_AS_BUILT = -24.66
# A stroke is "clearly heavier" (and becomes the space bar) when its energy in the first
# 50 ms is this much above the median of the others and it is not brighter than them.
HEAVY_DB = 3.0
ACTIONS = ("press", "release")


@dataclass(frozen=True)
class Source:
    file: str
    size: int
    blob: str  # git blob SHA-1 at TICKEYS_COMMIT
    fs_id: int
    title: str
    page_seconds: float  # duration shown on the Freesound page
    page_kb: str  # file size shown on the Freesound page

    @property
    def page(self) -> str:
        return f"https://freesound.org/people/jim-ph/sounds/{self.fs_id}/"


SOURCES = [
    Source("1.wav", 35788, "a0d3f8b6ae07de525c1a42a36813b9eb71250269", 194795,
           "Vintage Keyboard 1", 0.348, "34.9 KB"),
    Source("2.wav", 32326, "5bfb18b7a38d12bfc91e3e6ac7c28ddbd0633e35", 194796,
           "Vintage Keyboard 2", 0.299, "31.6 KB"),
    Source("3.wav", 33818, "450aa19ec507c607c9865e0fdbb621b71121d6bd", 194797,
           "Vintage Keyboard 3", 0.315, "33.0 KB"),
    Source("4.wav", 34012, "d6807bd7334500a18d22da8d2cca7641d2f81212", 194798,
           "Vintage Keyboard 4", 0.318, "33.2 KB"),
    Source("5.wav", 40298, "6bf5c06e88374278ef0794450a3f9ba9dfca0d44", 194799,
           "keyboard5.wav", 0.400, "39.4 KB"),
]
LICENSE_TXT = ("license.txt", 1303, "c7eb4c892aa90b20fbd4b7a0d7bd4bc26bf768d6")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--downloads", type=Path, required=True,
                    help="the folder given to fetch.sh")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "packs" / PACK_ID)
    ap.add_argument("--force", action="store_true",
                    help="replace an output folder that this script did not create")
    ap.add_argument("--skip-verify", action="store_true",
                    help="testing only: do not check sizes, SHA-1s and lengths")
    args = ap.parse_args()

    src_dir = args.downloads / "tickeys-mechanical"
    if not args.skip_verify:
        problems = [p for s in SOURCES for p in pl.verify_download(src_dir / s.file, s.size, s.blob)]
        problems += pl.verify_download(src_dir / LICENSE_TXT[0], LICENSE_TXT[1], LICENSE_TXT[2])
        if problems:
            print("download check failed:\n  " + "\n  ".join(problems), file=sys.stderr)
            return 1
    infos = {s.file: pl.probe(src_dir / s.file) for s in SOURCES}
    if not args.skip_verify:
        problems = []
        for s in SOURCES:
            seconds = infos[s.file]["duration"]
            if abs(seconds - s.page_seconds) > 0.0015:
                problems.append(f"{s.file}: {seconds:.4f} s, but {s.page} lists {s.page_seconds} s")
        if problems:
            print("download check failed:\n  " + "\n  ".join(problems), file=sys.stderr)
            return 1

    out = args.out
    if out.exists():
        sources_md = out / "SOURCES.md"
        ours = sources_md.is_file() and MARKER in sources_md.read_text(encoding="utf-8")
        if not ours and not args.force:
            print(f"{out} exists and was not made by this script; use --force", file=sys.stderr)
            return 1
        shutil.rmtree(out)

    # Decode and high-pass, then split each keystroke into its key-down and key-up.
    pre = round(pl.PRE_ROLL_S * RATE)
    splits: dict[str, pl.TapSplit] = {}
    floors: dict[str, float] = {}  # each take's noise floor, used to cut both its strokes
    parts: dict[tuple[str, str], np.ndarray] = {}
    for s in SOURCES:
        x = pl.highpass(pl.decode_mono(src_dir / s.file, RATE), RATE)
        sp = pl.split_tap(x, RATE)
        if sp is None:
            raise SystemExit(f"{s.file}: no separate key-up found; check the recording")
        splits[s.file] = sp
        floors[s.file] = pl.noise_floor(x, RATE)
        parts[s.file, "press"] = x[:sp.split]
        # From one pre-roll before release_from, so the key-up fades in from zero there.
        parts[s.file, "release"] = x[sp.release_from - pre:]

    # One gain for the whole pack: the key-downs' median peak to -6 dBFS, unless that would
    # put any file above the ceiling. Each key-up keeps its level next to its key-down.
    peaks = {k: pl.peak(x) for k, x in parts.items()}
    press_median = float(np.median([peaks[s.file, "press"] for s in SOURCES]))
    gain = pl.undb(pl.TARGET_MEDIAN_PEAK_DBFS) / press_median
    ceiling = pl.undb(pl.CEILING_DBFS)
    if max(peaks.values()) * gain > ceiling:
        gain = ceiling / max(peaks.values())
    # Headroom for the runtime's random volume boost and for peaks between samples.
    trim = pl.headroom_trim([x * gain for x in parts.values()], VARIATION["volume"])
    gain *= trim

    cuts: dict[tuple[str, str], tuple[np.ndarray, pl.Cut]] = {}
    for s in SOURCES:
        y, c = pl.cut(parts[s.file, "press"], RATE, MAX_SECONDS, gain, floor=floors[s.file])
        cuts[s.file, "press"] = (y * gain, c)
        if c.onset < round(0.001 * RATE):
            print(f"warning: {s.file} is audible from its first millisecond", file=sys.stderr)
        y, c = pl.cut(parts[s.file, "release"], RATE, MAX_SECONDS, gain, min_onset=pre,
                      floor=floors[s.file])
        shift = splits[s.file].release_from - pre
        c = dataclasses.replace(c, start=c.start + shift, onset=c.onset + shift,
                                end=c.end + shift)
        cuts[s.file, "release"] = (y * gain, c)

    # Pick a space bar only when one key-down is clearly heavier than the rest.
    weight = {}
    for s in SOURCES:
        y, c = cuts[s.file, "press"]
        head = y[c.onset - c.start:][: round(0.05 * RATE)]
        weight[s.file] = (pl.db(float(np.sqrt(np.mean(head * head)))),
                          pl.spectral_centroid(head, RATE))
    heaviest = max(SOURCES, key=lambda s: weight[s.file][0])
    others = [weight[s.file] for s in SOURCES if s is not heaviest]
    margin = weight[heaviest.file][0] - float(np.median([e for e, _ in others]))
    darker = weight[heaviest.file][1] <= float(np.median([c for _, c in others]))
    space = heaviest if margin >= HEAVY_DB and darker else None

    out.mkdir(parents=True)
    names: dict[tuple[str, str], str] = {}
    rendered: dict[str, np.ndarray] = {}
    n = 0
    for s in SOURCES:
        if s is not space:
            n += 1
        for a in ACTIONS:
            name = f"sounds/space-{a}.wav" if s is space else f"sounds/{a}-{n}.wav"
            names[s.file, a] = name
            pl.write_wav(out / name, cuts[s.file, a][0], RATE)
            rendered[name] = pl.read_wav16(out / name)[0]
    true_peaks = {f: pl.true_peak(x) for f, x in rendered.items()}
    headroom = max(true_peaks.values()) * (1.0 + VARIATION["volume"])
    if headroom > pl.undb(pl.MAX_TRUE_PEAK_DBFS + 0.05):
        raise SystemExit(f"loudest file reaches {pl.db(headroom):.2f} dBFS with the volume "
                         "variation; the headroom trim did not hold")

    groups: dict[str, dict[str, list[str]]] = {
        "alphanumeric": {a: [names[s.file, a] for s in SOURCES if s is not space]
                         for a in ACTIONS},
    }
    if space:
        groups["space"] = {a: [names[space.file, a]] for a in ACTIONS}
    manifest = {
        "format": 1,
        "id": PACK_ID,
        "name": "Vintage",
        "version": "1.0.0",
        "author": "jim-ph; packaged by TakTak contributors",
        "license": "CC0-1.0",
        "description": ("Crisp clacks from a 1986 DOS-era mechanical keyboard: five keystrokes, "
                        "each split into its own key-down and key-up, recorded with a condenser "
                        "microphone."),
        "source": (f"{PACK_PAGE} (mirrored with its Freesound license.txt by "
                   "https://github.com/yingDev/Tickeys)"),
        "attribution": "Recordings by jim-ph (Freesound, CC0 1.0), via Tickeys",
        "preview": "preview.wav",
        "volume": VOLUME,
        "trim_silence": True,
        "variation": dict(VARIATION),
        "groups": groups,
    }
    (out / "pack.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
                                   encoding="utf-8")

    preview_sounds = {f"k.{a}": [rendered[f] for f in groups["alphanumeric"][a]]
                      for a in ACTIONS}
    if space:
        preview_sounds.update({f"space.{a}": [rendered[names[space.file, a]]] for a in ACTIONS})
    script = ["k"] * 4 + ["space"] + ["k"] * 3 + ["space"] + ["k"] * 3 + ["enter"]
    preview = pl.render_preview(RATE, script, preview_sounds, seed=0x0B1D,
                                volume_variation=manifest["variation"]["volume"])
    pl.write_wav(out / "preview.wav", preview, RATE)

    sets = {f"{g}.{a}": files for g, ga in groups.items() for a, files in ga.items()}
    table = pl.stats_table(out, sets)
    if space:
        space_note = (f"`{names[space.file, 'press']}` ({space.title}) is {margin:.1f} dB "
                      "stronger in its first 50 ms than the median of the other key-downs and "
                      "no brighter, so it is the space bar (with its own key-up).")
    else:
        space_note = (f"The strongest key-down ({heaviest.title}) is only {margin:.1f} dB above "
                      f"the median of the others (or brighter than them), below the "
                      f"{HEAVY_DB:.0f} dB rule, so there is no separate space bar sound and every "
                      "key uses the same variants.")
    write_sources_md(out, src_dir, names, splits, cuts, infos, weight, gain, trim,
                     press_median * gain, true_peaks, space_note, table, args.skip_verify)
    print(table)
    print(f"\n{space_note}")
    total = sum(p.stat().st_size for p in out.rglob("*") if p.is_file())
    print(f"\nwrote {out} ({total} bytes)")
    return 0


def write_sources_md(out: Path, src_dir: Path, names: dict, splits: dict, cuts: dict,
                     infos: dict, weight: dict, gain: float, trim: float, press_median: float,
                     true_peaks: dict, space_note: str, table: str, unverified: bool) -> None:
    def sha(p: Path) -> str:
        return pl.sha256_file(p) if p.is_file() else "(missing)"

    stroke = {"press": "key-down", "release": "key-up"}
    dwell, left_out = pl.dwell_text(list(splits.values()))
    lines = [
        MARKER,
        "# Vintage: sources",
        "",
        "Generated by `tools/pack-sources/vintage-keyboard/build.py`. Rebuild with:",
        "",
        "```",
        "tools/pack-sources/vintage-keyboard/fetch.sh DOWNLOADS",
        "python3 tools/pack-sources/vintage-keyboard/build.py --downloads DOWNLOADS",
        "```",
        "",
        "## License",
        "",
        f"jim-ph's Freesound pack \"vintage keyboard\" ({PACK_PAGE}) has five sounds. On "
        f"{CHECKED} each sound's Freesound page showed **CC0 1.0** ({CC0_URL}), which allows "
        "copying, modifying and distributing, including commercially, without permission or "
        "credit; the pack page lists all five as \"Creative Commons 0\" too. The pack is "
        "`CC0-1.0`; the credit in `pack.json` is a courtesy. The description (a keystroke of "
        "a 1986 DOS mechanical keyboard, recorded with a condenser microphone) is from the "
        "Freesound pages.",
        "",
        "## Where the files came from",
        "",
        "Freesound needs a login to download, so the files come from the MIT-licensed Tickeys "
        f"app, which ships the pack unchanged with Freesound's own `license.txt` ({TICKEYS_TREE}). "
        "That license.txt lists the five sounds, each as Creative Commons 0. Tickeys renamed "
        "them `1.wav` … `5.wav`; each is matched to its Freesound sound by the duration and "
        "file size the Freesound page lists. Only this folder of Tickeys is used: its other "
        "sound folders have no stated origin.",
        "",
        "| Pack files | Freesound page | Author | Title | Freesound page lists | Direct download "
        "| SHA-256 of download | License (proof) | Checked |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for s in SOURCES:
        lines.append(
            f"| `{names[s.file, 'press']}`, `{names[s.file, 'release']}` | {s.page} | jim-ph "
            f"| {s.title} | WAV, 44.1 kHz 16-bit mono, {s.page_seconds:.3f} s, {s.page_kb} "
            f"| {TICKEYS_RAW}{s.file} | `{sha(src_dir / s.file)}` | CC0-1.0 ({s.page}, "
            f"{CC0_URL}; Tickeys license.txt) | {CHECKED} |")
    lines += [
        "",
        f"`license.txt` from the same folder: SHA-256 `{sha(src_dir / LICENSE_TXT[0])}`. Each "
        "download was checked against the size and git blob SHA-1 GitHub reported, and its "
        "length against its Freesound page "
        + ("(**skipped for this build: --skip-verify**)." if unverified else "(all matched)."),
        "",
        "## Each take is a whole keystroke",
        "",
        f"Every recording holds one keystroke: the key-down, then the key-up {dwell} later, "
        "with a quiet gap between them. Played whole on key-down, each would also sound a "
        "key-up at a fixed delay, whenever the key is actually released. So the build splits "
        "each take in two (`packlib.split_tap`): the key-up is the loudest moment at least "
        "60 ms after the key-down starts, its attack starts where the level (1 ms frames, "
        "walking back from that peak) first drops 20 dB below it, and the split is the middle "
        "of the quietest 5 ms between 30 ms after the key-down and 1 ms before that attack. "
        "The build stops unless that gap is at least 24 dB (RMS) below the key-up's peak. "
        "The key-down becomes the press sound and the same take's key-up its release sound: "
        "every release is a recorded key-up, none is made up. The key-up sound starts 5 ms "
        "before its attack (or at the split, if that is later); what lies between the split "
        f"and there (up to {left_out}, a soft noise in some takes) is left out, so that no "
        "key-up starts that far ahead of its click. Both strokes are cut against the whole "
        "take's noise floor.",
        "",
        "| Source file | Split (positions in the decoded source) |",
        "|---|---|",
    ]
    for s in SOURCES:
        lines.append(f"| `{s.file}` | {splits[s.file].describe()} |")
    lines += [
        "",
        "## How each file was made",
        "",
        f"All files: decoded at {RATE} Hz (the recordings' own rate, mono), 30 Hz 2nd-order "
        "Butterworth high-pass (also removes DC), split into key-down and key-up as above, "
        "each stroke cut as listed (0.5 ms raised-cosine fade-in before the onset; "
        f"raised-cosine fade-out ending on an exact zero; at most {MAX_SECONDS:.1f} s), one "
        f"gain of {pl.db(gain):+.2f} dB for the whole pack (the key-downs' median peak goes "
        f"to {pl.db(press_median):.0f} dBFS; the strokes keep their natural differences, and "
        "each key-up its level next to its own key-down), written as 16-bit PCM WAV. No other "
        "processing. Headroom: the loudest file's true peak (4x oversampled) is "
        f"{pl.db(max(true_peaks.values())):.2f} dBFS, and "
        f"{pl.db(max(true_peaks.values()) * (1 + VARIATION['volume'])):.2f} dBFS at the top "
        f"of the runtime's ±{VARIATION['volume']:.0%} volume variation (the rule is at most "
        f"{pl.MAX_TRUE_PEAK_DBFS:.0f} dBFS, as the mixer clips hard at 0 dBFS), so "
        + ("no headroom trim was needed." if trim >= 1.0 else
           f"the gain includes a {pl.db(trim):+.2f} dB headroom trim."),
        "",
        "| Pack file | Source file | Decoded source | Stroke | Cut | First 50 ms: energy, "
        "centroid | True peak | SHA-256 as shipped |",
        "|---|---|---|---|---|---|---:|---|",
    ]
    for s in SOURCES:
        info = infos[s.file]
        for a in ACTIONS:
            name = names[s.file, a]
            if a == "press":
                energy, centroid = weight[s.file]
                head = f"{energy:.1f} dBFS RMS, {centroid:.0f} Hz"
            else:
                head = "–"
            lines.append(
                f"| `{name}` | `{s.file}` | {info['codec']}, {info['rate']} Hz, "
                f"{info['channels']} ch | {stroke[a]} | {cuts[s.file, a][1].describe()} "
                f"| {head} | {pl.db(true_peaks[name]):.2f} dBFS | `{sha(out / name)}` |")
    lines += [
        "",
        space_note,
        "",
        f"`preview.wav` (SHA-256 `{sha(out / 'preview.wav')}`): just under 2 s of typing "
        "rendered from the pack's own files (4 keys, space, 3 keys, space, 3 keys, Enter, "
        "each with its key-up; 60–120 ms holds, 80–200 ms between presses, ±8% volume per "
        "stroke, fixed random seed; Space and Enter use the same strokes as every other key, "
        "as in the pack), scaled down only if it would peak above -1 dBFS.",
        "",
        "## Loudness",
        "",
        pl.loudness_text(PACK_ID, VOLUME, LK_AS_BUILT, VARIATION["volume"],
                         max(true_peaks.values())),
        "",
        "## Levels",
        "",
        table,
        "",
    ]
    (out / "SOURCES.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    sys.exit(main())
