#!/usr/bin/env python3
"""Builds packs/tactile from the files fetch.sh downloaded.

    tools/pack-sources/tactile/fetch.sh DOWNLOADS
    python3 tools/pack-sources/tactile/build.py --downloads DOWNLOADS [--out packs/tactile]

Every input is CC0-1.0 (checked on each Freesound page on 2026-10-02, see SOURCES.md).
The script checks each download against the size and git blob SHA-1 that GitHub reported for
clatterbox commit 9dca88f, so a changed upstream file stops the build.

Each recording is a whole tap: the key-down, then the key-up 90-170 ms later in the same take.
The build splits every take at the quietest point between the two strokes, so the key-down
plays on press and the take's own key-up on release (and a press never carries a key-up).

The StavSounds takes were recorded about 20 dB apart in loudness. Each take gets its own
levelling gain, which brings its key-down to within LEVEL_BAND_DB of the median take's
K-weighted loudness and keeps its key-up from going above that band (a take already inside
it is left as recorded); the gain applies to the whole take, so every take keeps its own
key-down/key-up balance. Two takes (DROPPED) are left out; SOURCES.md says why.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np

sys.dont_write_bytecode = True  # keep the source tree clean of __pycache__
sys.path.insert(0, str(Path(__file__).resolve().parent))
import packlib as pl  # noqa: E402

PACK_ID = "tactile"
CHECKED = "2026-10-02"
# Every file keeps its source's own rate (44.1 kHz, or 48 kHz for the Enter and backspace
# previews); the preview is mixed at RATE.
RATE = 44100
VARIATION = {"pitch": 0.015, "volume": 0.06}
CC0_URL = "https://creativecommons.org/publicdomain/zero/1.0/"
CLATTERBOX_COMMIT = "9dca88f4d151e24f243b5a9aafec7a60c809fb48"
CLATTERBOX_RAW = (f"https://raw.githubusercontent.com/zordhalo/clatterbox/{CLATTERBOX_COMMIT}"
                  "/src-tauri/resources/packs/tactile/")
CLATTERBOX_TREE = (f"https://github.com/zordhalo/clatterbox/tree/{CLATTERBOX_COMMIT}"
                   "/src-tauri/resources/packs/tactile")
REPO_ROOT = Path(__file__).resolve().parents[3]
MARKER = "<!-- generated by tools/pack-sources/tactile/build.py -->"

# Level of each source in the pack. First each StavSounds take is levelled with one gain for
# the take, the smallest (none for a take already inside the band) that puts its key-down's
# K-weighted loudness (pl.k_loudness) within LEVEL_BAND_DB of the median take's key-down and
# its key-up no louder than the top of that band; each take keeps its key-down/key-up
# balance. A take whose key-up is more than twice the band louder than its key-down cannot
# be levelled, and the build stops on it (it would sound like a late keystroke: the click
# comes when the key is let go). Then the levelled key-downs set the pack gain (it aims
# their median peak at -6 dBFS, capped so that no StavSounds file, key-down or key-up, peaks
# above the ceiling); the Enter and backspace recordings each get one gain that puts their
# key-down peak this many dB from the StavSounds key-downs' median peak as it ends up.
LEVEL_BAND_DB = 3.0
PRESS_MEDIAN_PEAK = pl.TARGET_MEDIAN_PEAK_DBFS
ROLE_OFFSET_DB = {"enter": 1.0, "backspace": 0.0}
MAX_SECONDS = 0.4
# The shipped strokes are measured again and must keep to the band within this much (the
# levelling is measured before the final gains and 16-bit rounding), or the build stops.
BAND_SLACK_DB = 0.5
# StavSounds takes that are decoded and measured but not used, with the reason (SOURCES.md
# adds the measurements). Their files are still numbered after their clatterbox download, so
# press-NN.wav and release-NN.wav always come from down-NN.mp3.
DROPPED = {
    "down-02.mp3": "a soft key-down that never bottomed out, then a hard top-out, so the "
                   "keystroke's click would come late, when the key is let go",
    "down-12.mp3": "the quietest key-down by far, with a key-up louder than it: it would need "
                   "by far the largest levelling boost, and its click would still come late, on "
                   "the key-up",
}
# Playback level, written to pack.json as "volume"; it changes no audio file. Measured on the
# built pack with
#     cargo run -p synth-packs --release -- loudness packs/tactile
# (tools/synth-packs/src/loudness.rs): typing reads LK_AS_BUILT at volume 1.0, and VOLUME puts
# it within the 0.5 dB tolerance of the reference (pl.REFERENCE_LK). VOLUME_FOR_REFERENCE is the
# volume the reference would take when headroom caps VOLUME below it, None otherwise. Recorded
# in SOURCES.md; re-measure whenever the processing here changes.
VOLUME = 0.98
LK_AS_BUILT = -26.07
VOLUME_FOR_REFERENCE: float | None = None


@dataclass(frozen=True)
class Source:
    file: str  # file name in clatterbox's pack (and in the download folder)
    size: int
    blob: str  # git blob SHA-1 at CLATTERBOX_COMMIT
    fs_id: int
    author: str
    title: str
    original: str  # the Freesound original, as its page describes it
    role: str  # key | enter | backspace
    stem: str  # output name stem: sounds/<stem>-press.wav or sounds/<stem>-release.wav,
    # or, for the StavSounds keys, sounds/press-NN.wav and sounds/release-NN.wav

    @property
    def page(self) -> str:
        return f"https://freesound.org/people/{self.author}/sounds/{self.fs_id}/"

    def out(self, action: str) -> str:
        if self.role == "key":
            return f"sounds/{action}-{self.stem}.wav"
        return f"sounds/{self.stem}-{action}.wav"


def _stav(n: int, file: str, size: int, blob: str, fs_id: int, title: str, original: str) -> Source:
    return Source(file, size, blob, fs_id, "StavSounds", title, original, "key", f"{n:02d}")


SOURCES = [
    _stav(1, "down-01.mp3", 4539, "ee763cce083b457b2d57c23cfe40c65ca7a0a36d", 766628,
          "Keyboard_Tactile_12", "Ogg Vorbis, 44.1 kHz stereo, 0.142 s"),
    _stav(2, "down-02.mp3", 6157, "7fd8c852f686e20d76db1f80688c9bf11d85220c", 766629,
          "Keyboard_Tactile_13", "Ogg Vorbis, 44.1 kHz stereo, 0.208 s"),
    _stav(3, "down-03.mp3", 5426, "758ce2f4cb5d2762c03e10afe31c3bf06e4dc3f8", 766630,
          "Keyboard_Tactile_14", "Ogg Vorbis, 44.1 kHz stereo, 0.178 s"),
    _stav(4, "down-04.mp3", 5114, "bb7b1c6b2948c7e2b202a4cdedae4202066b6858", 766631,
          "Keyboard_Tactile_15", "Ogg Vorbis, 44.1 kHz stereo, 0.159 s"),
    _stav(5, "down-05.mp3", 5635, "061749a668a4d7c898167b8feea2c5bc2e54671c", 766632,
          "Keyboard_Tactile_2", "Ogg Vorbis, 44.1 kHz stereo, 0.200 s"),
    _stav(6, "down-06.mp3", 6262, "c0b1e6c711dcf6b0e2fd51a470f4db3a8ae9e2e8", 766633,
          "Keyboard_Tactile_3", "Ogg Vorbis, 44.1 kHz stereo, 0.212 s"),
    _stav(7, "down-07.mp3", 5792, "28c682f9578260921b3f9071cc9c129ca9dc511f", 766634,
          "Keyboard_Tactile_4", "Ogg Vorbis, 44.1 kHz stereo, 0.195 s"),
    _stav(8, "down-08.mp3", 6835, "18c3c9749b050d8409191f3953f4cabcd2e58f14", 766635,
          "Keyboard_Tactile_5", "Ogg Vorbis, 44.1 kHz stereo, 0.256 s"),
    _stav(9, "down-09.mp3", 5113, "11191c962543a6d6490939769397b9b7d2ed7968", 766637,
          "Keyboard_Tactile_6", "Ogg Vorbis, 44.1 kHz stereo, 0.172 s"),
    _stav(10, "down-10.mp3", 5948, "22bb1e3927f93bcb0badaf5315301f44ceec985e", 766638,
          "Keyboard_Tactile_7", "Ogg Vorbis, 44.1 kHz stereo, 0.203 s"),
    _stav(11, "down-11.mp3", 6261, "1e06949e3af36abf373420aebe805e7cc689013a", 766639,
          "Keyboard_Tactile_8", "Ogg Vorbis, 44.1 kHz stereo, 0.218 s"),
    _stav(12, "down-12.mp3", 5897, "05a52b17ec0c0b2817b96b5bb6828e7e967e58c3", 766640,
          "Keyboard_Tactile_9", "Ogg Vorbis, 44.1 kHz stereo, 0.193 s"),
    Source("enter-down-01.mp3", 7008, "eaaed01cea814d5f223754e6f1744f2ee2fc11f7", 627647,
           "alpinemesh", "Enter Key Press Mechanical Keyboard",
           "WAV, 48 kHz 24-bit mono, 0.182 s; Enter key of a Corsair K70 RGB",
           "enter", "enter"),
    Source("backspace-down-01.mp3", 6144, "23dbb43eb18db43662a8d34592a9d721031d9200", 380141,
           "yottasounds", "Computer Keyboard - single key - type 2.wav",
           "WAV, 96 kHz 32-bit stereo, 0.220 s; keyboard model not stated",
           "backspace", "backspace"),
]
PROVENANCE_DOCS = [
    ("CREDITS.md", 2724, "3aba868144ef1e75bde0a526da37a4a24bad34f9"),
    ("pack.toml", 603, "a884412b74e4dd36972815bc891527812d16c7c7"),
]
ACTIONS = ("press", "release")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--downloads", type=Path, required=True,
                    help="the folder given to fetch.sh")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "packs" / PACK_ID)
    ap.add_argument("--force", action="store_true",
                    help="replace an output folder that this script did not create")
    ap.add_argument("--skip-verify", action="store_true",
                    help="testing only: do not check sizes and SHA-1s (SOURCES.md says so)")
    args = ap.parse_args()

    src_dir = args.downloads / "clatterbox-tactile"
    if not args.skip_verify:
        problems = [p for s in SOURCES for p in pl.verify_download(src_dir / s.file, s.size, s.blob)]
        problems += [p for f, size, blob in PROVENANCE_DOCS
                     for p in pl.verify_download(src_dir / f, size, blob)]
        if problems:
            print("download check failed:\n  " + "\n  ".join(problems), file=sys.stderr)
            return 1

    out = args.out
    if out.exists():
        sources_md = out / "SOURCES.md"
        ours = sources_md.is_file() and MARKER in sources_md.read_text(encoding="utf-8")
        if not ours and not args.force:
            print(f"{out} exists and was not made by this script; use --force", file=sys.stderr)
            return 1
        shutil.rmtree(out)

    # Decode and high-pass every recording at its own sample rate, then split each tap into
    # its key-down (press) and key-up (release).
    infos: dict[str, dict] = {}
    rates: dict[str, int] = {}
    splits: dict[str, pl.TapSplit] = {}
    floors: dict[str, float] = {}  # each take's noise floor, used to cut both its strokes
    parts: dict[tuple[str, str], np.ndarray] = {}
    for s in SOURCES:
        path = src_dir / s.file
        infos[s.file] = pl.probe(path)
        rates[s.file] = infos[s.file]["rate"]
        x = pl.highpass(pl.decode_mono(path, rates[s.file]), rates[s.file])
        sp = pl.split_tap(x, rates[s.file])
        if sp is None:
            raise SystemExit(f"{s.file}: no separate key-up found; check the recording")
        splits[s.file] = sp
        floors[s.file] = pl.noise_floor(x, rates[s.file])
        parts[s.file, "press"] = x[:sp.split]
        # From one pre-roll before release_from, so the key-up fades in from zero there.
        parts[s.file, "release"] = x[sp.release_from - pre_roll(rates[s.file]):]

    unknown = set(DROPPED) - {s.file for s in SOURCES if s.role == "key"}
    if unknown:
        raise SystemExit(f"DROPPED names files that are not StavSounds takes: {sorted(unknown)}")
    used = [s for s in SOURCES if s.file not in DROPPED]
    keys = [s for s in used if s.role == "key"]

    # Loudness of every StavSounds stroke as recorded, measured as synth-packs does (first
    # 100 ms, K-weighted) on the stroke as it would be cut at unity gain.
    takes = [s for s in SOURCES if s.role == "key"]
    recorded_lk: dict[tuple[str, str], float] = {}
    for s in takes:
        rate = rates[s.file]
        recorded_lk[s.file, "press"] = pl.k_loudness(
            pl.cut(parts[s.file, "press"], rate, MAX_SECONDS, 1.0, floor=floors[s.file])[0], rate)
        recorded_lk[s.file, "release"] = pl.k_loudness(
            pl.cut(parts[s.file, "release"], rate, MAX_SECONDS, 1.0, min_onset=pre_roll(rate),
                   floor=floors[s.file])[0], rate)

    # Levelling: one gain per kept take, the smallest that puts its key-down within
    # LEVEL_BAND_DB of the median take's and its key-up no louder than the band's top.
    median_lk = float(np.median([recorded_lk[s.file, "press"] for s in keys]))
    level: dict[str, float] = {}
    for s in keys:
        gain_db = level_gain_db(recorded_lk[s.file, "press"], recorded_lk[s.file, "release"],
                                median_lk, LEVEL_BAND_DB)
        if gain_db is None:
            up_over_down = recorded_lk[s.file, "release"] - recorded_lk[s.file, "press"]
            raise SystemExit(f"{s.file}: its key-up is {up_over_down:.1f} dB louder than its "
                             "key-down, more than the levelling band allows; check the split, "
                             "or list the take in DROPPED")
        level[s.file] = pl.undb(gain_db)

    # One gain per source on top of that. StavSounds: levelled key-down median peak to
    # -6 dBFS, capped so that no StavSounds file peaks above the ceiling. Enter and backspace:
    # their key-down at the role offset from where that median lands.
    peaks = {k: pl.peak(x) for k, x in parts.items()}
    press_median = float(np.median([peaks[s.file, "press"] * level[s.file] for s in keys]))
    key_gain = pl.undb(PRESS_MEDIAN_PEAK) / press_median
    ceiling = pl.undb(pl.CEILING_DBFS)
    loudest = max(peaks[s.file, a] * level[s.file] for s in keys for a in ACTIONS) * key_gain
    if loudest > ceiling:
        key_gain *= ceiling / loudest
    gains: dict[str, float] = {}
    for s in used:
        if s.role == "key":
            gains[s.file] = key_gain * level[s.file]
        else:
            target = press_median * key_gain * pl.undb(ROLE_OFFSET_DB[s.role])
            gains[s.file] = target / peaks[s.file, "press"]

    # Headroom: one trim for every file, so the balance between them is unchanged.
    trim = pl.headroom_trim([parts[s.file, a] * gains[s.file] for s in used for a in ACTIONS],
                            VARIATION["volume"])
    gains = {f: g * trim for f, g in gains.items()}
    press_median_out = press_median * key_gain * trim

    # Trim each stroke: the onset is where it will reach the loader's silence threshold.
    # Cut positions are kept relative to the decoded source (the key-up starts at the split).
    cuts: dict[tuple[str, str], tuple[np.ndarray, pl.Cut]] = {}
    for s in used:
        rate = rates[s.file]
        for a in ACTIONS:
            if a == "press":
                y, c = pl.cut(parts[s.file, a], rate, MAX_SECONDS, gains[s.file],
                              floor=floors[s.file])
            else:
                pre = pre_roll(rate)
                y, c = pl.cut(parts[s.file, a], rate, MAX_SECONDS, gains[s.file], min_onset=pre,
                              floor=floors[s.file])
                shift = splits[s.file].release_from - pre
                c = dataclasses.replace(c, start=c.start + shift, onset=c.onset + shift,
                                        end=c.end + shift)
            cuts[s.file, a] = (y, c)

    out.mkdir(parents=True)
    rendered: dict[str, np.ndarray] = {}
    for s in used:
        for a in ACTIONS:
            name = s.out(a)
            pl.write_wav(out / name, cuts[s.file, a][0] * gains[s.file], rates[s.file])
            # The preview is mixed at RATE: a file at another rate is resampled for it by ffmpeg.
            if rates[s.file] == RATE:
                rendered[name] = pl.read_wav16(out / name)[0]
            else:
                rendered[name] = pl.decode_mono(out / name, RATE)
    true_peaks = {s.out(a): pl.true_peak(pl.read_wav16(out / s.out(a))[0])
                  for s in used for a in ACTIONS}
    headroom = max(true_peaks.values()) * (1.0 + VARIATION["volume"])
    if headroom > pl.undb(pl.MAX_TRUE_PEAK_DBFS + 0.05):
        raise SystemExit(f"loudest file reaches {pl.db(headroom):.2f} dBFS with the volume "
                         "variation; the headroom trim did not hold")

    # The shipped strokes, measured as synth-packs measures them: the levelling must hold, so
    # that a few loud takes cannot carry a pack whose typical keystroke is much quieter.
    shipped_lk = {(s.file, a): pl.k_loudness(*pl.read_wav16(out / s.out(a)))
                  for s in keys for a in ACTIONS}
    shared_db = pl.db(key_gain * trim)
    band = (median_lk - LEVEL_BAND_DB + shared_db, median_lk + LEVEL_BAND_DB + shared_db)
    for (file, a), lk in shipped_lk.items():
        if lk > band[1] + BAND_SLACK_DB or (a == "press" and lk < band[0] - BAND_SLACK_DB):
            raise SystemExit(f"{file} {stroke_name(a)} ships at {lk:.1f} LK, outside the "
                             f"levelling band {band[0]:.1f}..{band[1]:.1f} LK")
    shipped_downs = [shipped_lk[s.file, "press"] for s in keys]

    groups: dict[str, dict[str, list[str]]] = {
        "alphanumeric": {a: [s.out(a) for s in keys] for a in ACTIONS},
    }
    for role in ("enter", "backspace"):
        groups[role] = {a: [s.out(a) for s in used if s.role == role] for a in ACTIONS}

    manifest = build_manifest(groups, len(keys))
    (out / "pack.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
                                   encoding="utf-8")

    preview_sounds = {f"{token}.{a}": [rendered[f] for f in groups[group][a]]
                      for token, group in (("k", "alphanumeric"), ("enter", "enter"))
                      for a in ACTIONS}
    script = ["k"] * 4 + ["space"] + ["k"] * 3 + ["space"] + ["k"] * 3 + ["enter"]
    preview = pl.render_preview(RATE, script, preview_sounds, seed=0x7AC711E,
                                volume_variation=manifest["variation"]["volume"])
    pl.write_wav(out / "preview.wav", preview, RATE)

    sets = {f"{g}.{a}": files for g, ga in groups.items() for a, files in ga.items()}
    table = pl.stats_table(out, sets)
    write_sources_md(out, src_dir, splits, cuts, infos, gains, trim, press_median_out,
                     true_peaks, table, args.skip_verify,
                     Levelling(recorded_lk, median_lk, level, shipped_lk))
    print(table)
    print(f"\nkey-downs as shipped: {max(shipped_downs) - min(shipped_downs):.1f} dB spread, "
          f"median {float(np.median(shipped_downs)):.2f} LK, power average "
          f"{pl.power_mean_db(shipped_downs):.2f} LK (at volume 1.0)")
    total = sum(p.stat().st_size for p in out.rglob("*") if p.is_file())
    print(f"\nwrote {out} ({total} bytes)")
    return 0


def pre_roll(rate: int) -> int:
    return round(pl.PRE_ROLL_S * rate)


def stroke_name(action: str) -> str:
    return {"press": "key-down", "release": "key-up"}[action]


def level_gain_db(down_lk: float, up_lk: float, median_lk: float, band_db: float) -> float | None:
    """A take's levelling gain in dB: the smallest that puts its key-down within band_db of
    median_lk and its key-up no louder than median_lk + band_db (0 when it already is), or
    None when no gain can, because the key-up is more than 2 * band_db above the key-down."""
    lowest = median_lk - band_db - down_lk
    highest = min(median_lk + band_db - down_lk, median_lk + band_db - up_lk)
    if lowest > highest:
        return None
    return min(max(0.0, lowest), highest)


@dataclass(frozen=True)
class Levelling:
    """The per-take levelling, for SOURCES.md."""

    recorded_lk: dict  # (file, action) -> LK of the stroke as recorded (unity gain)
    median_lk: float  # median recorded key-down LK of the kept takes
    level: dict  # file -> levelling gain (linear) of each kept take
    shipped_lk: dict  # (file, action) -> LK of the stroke as shipped (volume 1.0)


NUMBER_WORDS = {8: "eight", 9: "nine", 10: "ten", 11: "eleven", 12: "twelve"}


def build_manifest(groups: dict, taps: int) -> dict:
    return {
        "format": 1,
        "id": PACK_ID,
        "name": "Tactile",
        "version": "1.0.0",
        "author": "StavSounds, alpinemesh, yottasounds; packaged by TakTak contributors",
        "license": "CC0-1.0",
        "description": (f"Bright, snappy tactile switches: {NUMBER_WORDS.get(taps, str(taps))} "
                        "taps on a tactile mechanical keyboard, each split into its own key-down "
                        "and key-up, plus an Enter recorded on a Corsair K70 RGB."),
        "source": ("Freesound: https://freesound.org/people/StavSounds/packs/42151/ "
                   "https://freesound.org/people/alpinemesh/sounds/627647/ "
                   "https://freesound.org/people/yottasounds/sounds/380141/ "
                   "(previews mirrored by https://github.com/zordhalo/clatterbox)"),
        "attribution": ("Recordings by StavSounds, alpinemesh and yottasounds (Freesound, "
                        "CC0 1.0), via clatterbox"),
        "preview": "preview.wav",
        "volume": VOLUME,
        "trim_silence": True,
        "variation": dict(VARIATION),
        "groups": groups,
    }


def write_sources_md(out: Path, src_dir: Path, splits: dict, cuts: dict, infos: dict,
                     gains: dict, trim: float, press_median: float, true_peaks: dict,
                     table: str, unverified: bool, lev: Levelling) -> None:
    def sha(p: Path) -> str:
        return pl.sha256_file(p) if p.is_file() else "(missing)"

    used = [s for s in SOURCES if s.file not in DROPPED]
    keys = [s for s in used if s.role == "key"]
    dwell, left_out = pl.dwell_text([splits[s.file] for s in used])
    shipped = [lev.shipped_lk[s.file, "press"] for s in keys]
    shipped_ups = [lev.shipped_lk[s.file, "release"] for s in keys]
    lines = [
        MARKER,
        "# Tactile: sources",
        "",
        "Generated by `tools/pack-sources/tactile/build.py`. Rebuild with:",
        "",
        "```",
        "tools/pack-sources/tactile/fetch.sh DOWNLOADS",
        "python3 tools/pack-sources/tactile/build.py --downloads DOWNLOADS",
        "```",
        "",
        "## License",
        "",
        f"Every recording is dedicated to the public domain under **CC0 1.0** ({CC0_URL}), as "
        f"shown on its Freesound page on {CHECKED}. CC0 allows copying, modifying and "
        "distributing, including commercially, without permission or credit. The pack is "
        "`CC0-1.0`; the credit in `pack.json` is a courtesy. CC0 does not grant trademark "
        "rights, so the pack's name avoids brand names and the hardware is named only to "
        "describe the recordings. The StavSounds pack page "
        "(https://freesound.org/people/StavSounds/packs/42151/) also lists each of the 12 "
        f"taps as \"Creative Commons 0\" ({len(keys)} of them are used, see \"Not used\"), and "
        "clatterbox's `CREDITS.md` (below) says each file's page was checked one by one.",
        "",
        "## Where the files came from",
        "",
        "Freesound needs a login to download originals, so this pack uses the Freesound HQ "
        "MP3 previews that clatterbox (Apache-2.0 code; its README says the bundled CC0 audio "
        "is public domain and not under Apache) committed unchanged, with per-file credits, at "
        f"commit `{CLATTERBOX_COMMIT}`: {CLATTERBOX_TREE}. A CC0 dedication covers the work, so "
        "a preview of a CC0 sound is CC0 too.",
        "",
        "| Pack files | Freesound page | Author | Title | Freesound original | Direct download "
        "| SHA-256 of download | License (proof) | Checked |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for s in used:
        lines.append(
            f"| `{s.out('press')}`, `{s.out('release')}` | {s.page} | {s.author} | {s.title} "
            f"| {s.original} | {CLATTERBOX_RAW}{s.file} | `{sha(src_dir / s.file)}` "
            f"| CC0-1.0 ({s.page}, {CC0_URL}) | {CHECKED} |")
    lines += [
        "",
        "Provenance files downloaded from the same commit and checked: "
        + ", ".join(f"`{f}` (SHA-256 `{sha(src_dir / f)}`)" for f, _, _ in PROVENANCE_DOCS)
        + ". Each download (also the takes under \"Not used\") was checked against the size "
        + "and git blob SHA-1 GitHub reported "
        + ("(**skipped for this build: --skip-verify**)." if unverified else "for that commit."),
        "",
        "## Each take is a whole tap",
        "",
        "Every recording holds one tap: the key-down, then the key-up after the finger's "
        f"dwell, {dwell} later, with a quiet gap between them (clatterbox ships the takes as "
        "they are, as key-down sounds). Played whole on key-down, each would also sound a "
        "key-up at a fixed delay, whenever the key is actually released. So the build splits "
        "each take in two (`packlib.split_tap`): the key-up is the loudest moment at least "
        "60 ms after the key-down starts, its attack starts where the level (1 ms frames, "
        "walking back from that peak) first drops 20 dB below it, and the split is the middle "
        "of the quietest 5 ms between 30 ms after the key-down and 1 ms before that attack. "
        "The build stops unless that gap is at least 24 dB (RMS) below the key-up's peak. "
        "The key-down becomes the press sound and the same take's key-up its release sound: "
        "every release is a recorded key-up, none is made up. The key-up sound starts 5 ms "
        "before its attack (or at the split, if that is later); what lies between the split "
        f"and there (up to {left_out}, a soft noise in some takes) is left out, so that no "
        "key-up starts that far ahead of its click. Both strokes are cut against the whole "
        "take's noise floor.",
        "",
        "| Source file | Split (positions in the decoded source) |",
        "|---|---|",
    ]
    for s in used:
        lines.append(f"| `{s.file}` | {splits[s.file].describe()} |")
    lines += [
        "",
        "## Levelling",
        "",
        "The StavSounds takes were recorded at very different strengths: as recorded, the "
        f"key-downs of all {len(lev.level) + len(DROPPED)} takes span "
        f"{spread_lk(lev, [s for s in SOURCES if s.role == 'key']):.1f} dB of loudness, and "
        f"those of the {len(keys)} used takes {spread_lk(lev, keys):.1f} dB. With one gain for "
        "all of them, the typical keystroke played far below the few loudest ones (and below "
        "the other packs). Loudness here is what `synth-packs loudness` measures per sample: the "
        "K-weighted (ITU-R BS.1770) energy of the first 100 ms (`packlib.k_loudness`, on the "
        "stroke as cut at unity gain). Each take gets one levelling gain (`level_gain_db`), "
        f"the smallest that puts its key-down within {LEVEL_BAND_DB:.0f} dB of the median "
        f"take's key-down ({lev.median_lk:.1f} LK as recorded) and its key-up no louder than "
        "the top of that band. A take already inside the band keeps its recorded level, so "
        f"the natural variation within ±{LEVEL_BAND_DB:.0f} dB stays, and the gain applies to "
        "the whole take, so each take keeps its own key-down/key-up balance. The build stops "
        f"on a take whose key-up is more than {2.0 * LEVEL_BAND_DB:.0f} dB louder than its "
        "key-down (no gain can level it), and if any shipped stroke falls outside the band "
        f"(with {BAND_SLACK_DB:.1f} dB of slack for measuring before the final gain). As "
        f"shipped, the key-downs span {max(shipped) - min(shipped):.1f} dB, with a median of "
        f"{float(np.median(shipped)):.1f} LK and a power average of "
        f"{pl.power_mean_db(shipped):.1f} LK at volume 1.0; the key-ups have a median of "
        f"{float(np.median(shipped_ups)):.1f} LK and none is above {max(shipped_ups):.1f} LK.",
        "",
        "| Take | Key-down as recorded, re the median take | Key-up re its own key-down "
        "| Levelling gain | Key-down as shipped | Key-up as shipped |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for s in keys:
        press_lk = lev.recorded_lk[s.file, "press"]
        lines.append(
            f"| `{s.file}` | {press_lk - lev.median_lk:+.1f} dB "
            f"| {lev.recorded_lk[s.file, 'release'] - press_lk:+.1f} dB "
            f"| {pl.db(lev.level[s.file]):+.2f} dB | {lev.shipped_lk[s.file, 'press']:.1f} LK "
            f"| {lev.shipped_lk[s.file, 'release']:.1f} LK |")
    lines += [
        "",
        "## How each file was made",
        "",
        "All files: decoded with ffmpeg at the download's own sample rate (44.1 kHz, or 48 kHz "
        "for the Enter and backspace previews; no resampling), channels averaged to mono, "
        "30 Hz 2nd-order Butterworth high-pass (also removes DC), split into key-down and "
        "key-up as above, each stroke cut as listed (0.5 ms raised-cosine fade-in before the "
        "onset; raised-cosine fade-out ending on an exact zero; at most "
        f"{MAX_SECONDS:.1f} s), one gain per take (the levelling gain above, times one gain "
        "shared by all StavSounds takes) or per source (Enter, backspace), then one headroom "
        "trim for the whole pack, written as 16-bit PCM WAV at the download's rate. No other "
        "processing.",
        "",
        f"Gains: the {len(keys)} levelled StavSounds takes share one gain that aims the "
        f"key-downs' median peak at {PRESS_MEDIAN_PEAK:.0f} dBFS, capped so that no StavSounds "
        f"file (key-down or key-up) peaks above {pl.CEILING_DBFS:.1f} dBFS. After levelling, "
        f"the key-downs span about {spread_db(cuts, 'press', lev):.0f} dB of peak level and "
        f"the key-ups about {spread_db(cuts, 'release', lev):.0f} dB. After the headroom trim "
        f"below, the key-downs' median peak is {pl.db(press_median):.1f} dBFS. The Enter's "
        f"key-down peaks {offset_text(ROLE_OFFSET_DB['enter'])} and the backspace key's "
        f"{offset_text(ROLE_OFFSET_DB['backspace'])}; their key-ups keep their recorded "
        "level next to their key-down. Headroom: the mixer clips hard at 0 dBFS, resampling "
        "to the device rate can peak between samples, and the runtime adds up to "
        f"+{VARIATION['volume']:.0%} of random volume per keystroke. So every gain is then "
        f"scaled by {pl.db(trim):+.2f} dB, which keeps the loudest file's true peak (4x "
        f"oversampled) at {pl.db(max(true_peaks.values())):.2f} dBFS, and at "
        f"{pl.db(max(true_peaks.values()) * (1 + VARIATION['volume'])):.2f} dBFS at the top "
        f"of the volume variation (the rule is at most {pl.MAX_TRUE_PEAK_DBFS:.0f} dBFS). No "
        "sample reaches full scale (the highest sample peak is "
        f"{pl.db(max(pl.peak(pl.read_wav16(out / name)[0]) for name in true_peaks)):.2f} "
        "dBFS). The Gain column is the total.",
        "",
        "| Pack file | Source file | Decoded source | Stroke | Cut | Gain | True peak "
        "| SHA-256 as shipped |",
        "|---|---|---|---|---|---:|---:|---|",
    ]
    for s in used:
        info = infos[s.file]
        for a in ACTIONS:
            name = s.out(a)
            lines.append(
                f"| `{name}` | `{s.file}` | {info['codec']}, {info['rate']} Hz, "
                f"{info['channels']} ch | {stroke_name(a)} | {cuts[s.file, a][1].describe()} "
                f"| {pl.db(gains[s.file]):+.2f} dB | {pl.db(true_peaks[name]):.2f} dBFS "
                f"| `{sha(out / name)}` |")
    lines += [
        "",
        f"`preview.wav` (SHA-256 `{sha(out / 'preview.wav')}`): just under 2 s of typing at "
        f"{RATE} Hz rendered from the pack's own files (4 keys, space, 3 keys, space, 3 keys, "
        "Enter, each with its key-up; 60–120 ms holds, 80–200 ms between presses, ±6% volume "
        "per stroke, fixed random seed; the 48 kHz Enter files are resampled to 44.1 kHz by "
        "ffmpeg for this mix only), scaled down only if it would peak above -1 dBFS.",
        "",
        "## Loudness",
        "",
        pl.loudness_text(PACK_ID, VOLUME, LK_AS_BUILT, VARIATION["volume"],
                         max(true_peaks.values()), VOLUME_FOR_REFERENCE),
        "",
        "## Not used",
        "",
    ]
    for s in SOURCES:
        if s.file not in DROPPED:
            continue
        press_lk = lev.recorded_lk[s.file, "press"]
        release_lk = lev.recorded_lk[s.file, "release"]
        needed = level_gain_db(press_lk, release_lk, lev.median_lk, LEVEL_BAND_DB)
        lines.append(
            f"- StavSounds' \"{s.title}\" ({s.page}, CC0; clatterbox's `{s.file}`, SHA-256 "
            f"`{sha(src_dir / s.file)}`): {DROPPED[s.file]}. Measured as under \"Levelling\", "
            f"its key-down is {press_lk - lev.median_lk:+.1f} dB from the median of the used "
            f"takes and its key-up {release_lk - press_lk:+.1f} dB from its key-down; "
            + ("no levelling gain fits it." if needed is None
               else f"levelling it would take {needed:+.1f} dB."))
    lines += [
        "- Foxfire-'s \"Keyboard - Key release\" "
        "(https://freesound.org/people/Foxfire-/sounds/570755/, CC0; clatterbox's `up-01.mp3`): "
        "a key-up from a different keyboard (Cherry MX Brown). Every take above carries its own "
        "key-up, so the pack uses those instead.",
        "- Foxfire-'s matching press, \"Keyboard - Press down\" "
        "(https://freesound.org/people/Foxfire-/sounds/570754/, CC0): Freesound needs a login "
        f"to download it, and on {CHECKED} no mirror without a login was found.",
        "",
        "## Levels",
        "",
        table,
        "",
    ]
    (out / "SOURCES.md").write_text("\n".join(lines), encoding="utf-8")


def offset_text(offset_db: float) -> str:
    """Where a role's key-down peak sits relative to the key-downs' median peak, in words."""
    if abs(offset_db) < 0.05:
        return "level with that median"
    return f"{abs(offset_db):.0f} dB {'above' if offset_db > 0 else 'below'} that median"


def spread_lk(lev: Levelling, keys: list[Source]) -> float:
    """dB between the loudest and the quietest of these takes' key-downs, as recorded."""
    values = [lev.recorded_lk[s.file, "press"] for s in keys]
    return max(values) - min(values)


def spread_db(cuts: dict, action: str, lev: Levelling) -> float:
    """dB of peak level between the loudest and the quietest used StavSounds stroke of one
    kind, after levelling."""
    peaks = [pl.peak(cuts[s.file, action][0]) * lev.level[s.file]
             for s in SOURCES if s.role == "key" and s.file not in DROPPED]
    return pl.db(max(peaks)) - pl.db(min(peaks))


if __name__ == "__main__":
    sys.exit(main())
