//! Generates TakTak's bundled packs (Deep Thock, Crisp Clack, Blue Click) by physically
//! informed synthesis, so they are our own work and can be released as CC0-1.0.
//!
//! Output is deterministic: every sample is seeded from its pack id and file name, so a
//! re-run on the same platform rewrites byte-identical files.
//!
//! `synth-packs loudness` measures any pack's typing loudness the same way, so recorded packs
//! can be matched to the synthesized ones (see `loudness.rs`).

mod analysis;
mod dsp;
mod layout;
mod loudness;
mod pack;
mod params;
mod render;
mod sha256;

use std::path::PathBuf;
use std::process::ExitCode;

const USAGE: &str = "\
synth-packs: generate TakTak's bundled, synthesized sound packs.

USAGE
  synth-packs [--out DIR]
  synth-packs loudness [--target LK] [--check] PACK...

  --out DIR     where to write the packs, one folder per pack id (default: packs)

Each pack folder gets pack.json, sounds/, preview.wav and SOURCES.md (provenance and the
SHA-256 of every file). Existing pack folders are replaced only if they were generated by
synth-packs.

loudness measures each PACK (folder or .zip) as TakTak plays it by default: K-weighted
(BS.1770) level of the first 100 ms of the sample each alphanumeric key plays on press,
power-averaged over the keys, in LK, with and without the pack's volume, and the volume that
would match the target.

  --target LK   reference typing loudness (default: -25.8, the synthesized packs)
  --check       exit with status 1 if a pack is off target (more than 0.5 dB away although
                its volume could fix it, or too hot for the -1 dBFS true-peak headroom rule)
";

fn main() -> ExitCode {
    let mut out = PathBuf::from("packs");
    let mut args = std::env::args().skip(1).peekable();
    if args.peek().map(String::as_str) == Some("loudness") {
        return loudness_command(args.skip(1));
    }
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--out" => match args.next() {
                Some(dir) => out = PathBuf::from(dir),
                None => return usage_error("--out needs a directory"),
            },
            "-h" | "--help" => {
                print!("{USAGE}");
                return ExitCode::SUCCESS;
            }
            other => return usage_error(&format!("unknown argument {other:?}")),
        }
    }

    match pack::generate(&out, &params::PACKS) {
        Ok(reports) => {
            print_reports(&out, &reports);
            ExitCode::SUCCESS
        }
        Err(e) => {
            eprintln!("synth-packs: {e}");
            ExitCode::FAILURE
        }
    }
}

fn loudness_command(args: impl Iterator<Item = String>) -> ExitCode {
    let mut args = args;
    let (mut target, mut check, mut paths) = (loudness::REFERENCE_LK, false, Vec::new());
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--target" => match args.next().and_then(|v| v.parse::<f64>().ok()) {
                Some(v) if v.is_finite() => target = v,
                _ => return usage_error("--target needs a level in LK, e.g. -25.8"),
            },
            "--check" => check = true,
            "-h" | "--help" => {
                print!("{USAGE}");
                return ExitCode::SUCCESS;
            }
            other if other.starts_with('-') => {
                return usage_error(&format!("unknown argument {other:?}"));
            }
            path => paths.push(PathBuf::from(path)),
        }
    }
    if paths.is_empty() {
        return usage_error("loudness needs at least one pack");
    }
    println!("{}", loudness::TABLE_HEADER);
    let mut failed = 0;
    for path in &paths {
        match loudness::measure(path) {
            Ok(l) => {
                println!("{}", loudness::table_row(&l, target));
                if l.status(target) == loudness::Status::Off {
                    failed += 1;
                }
            }
            Err(e) => {
                failed += 1;
                println!("{e}");
            }
        }
    }
    println!(
        "\nLK = K-weighted (BS.1770) level of the first 100 ms of the sample each alphanumeric key\n\
         plays on press by default (rel-press: the same for release), power-averaged over the\n\
         keys, on the samples as the app loads them at 48 kHz; n = distinct samples those are.\n\
         raw = as stored, eff = with the pack's volume; target {target:.1} LK, tolerance {:.1} dB.\n\
         true peak eff = loudest true peak any key can play (4x oversampled) times the volume\n\
         and the top of the volume variation; the max clean volume keeps it at or below {:.0}\n\
         dBFS. status: ok = on target; limited = quieter, but at the max clean volume; OFF =\n\
         fix the volume (or the build gain).",
        loudness::TOLERANCE_DB,
        loudness::MAX_TRUE_PEAK_DBFS
    );
    if check && failed > 0 {
        println!("{failed} of {} packs are off target or failed to load", paths.len());
        return ExitCode::FAILURE;
    }
    ExitCode::SUCCESS
}

fn usage_error(msg: &str) -> ExitCode {
    eprintln!("synth-packs: {msg}\n\n{USAGE}");
    ExitCode::from(2)
}

fn print_reports(out: &std::path::Path, reports: &[pack::PackReport]) {
    for r in reports {
        println!(
            "\n{} ({}): {} files, {:.2} MB, pack gain {:+.1} dB, preview {:.2} s -> {}",
            r.name,
            r.id,
            r.files,
            r.bytes as f64 / 1e6,
            r.gain_db,
            r.preview_ms / 1e3,
            out.join(r.id).display()
        );
        println!("{}", analysis::TABLE_HEADER);
        for (group, action, s) in &r.rows {
            println!("{}", analysis::table_row(group, action, s));
        }
    }
    println!("\nTyping summary (per-key alphanumeric samples):");
    println!(
        "pack           LK press  release-press dB  centroid press/release Hz  attack Hz  crest dB"
    );
    for r in reports {
        println!(
            "{:<14} {:>8.1} {:>17.1} {:>15.0} / {:<8.0} {:>10.0} {:>9.1}",
            r.id,
            r.typing.k_db,
            r.typing_release.k_db - r.typing.k_db,
            r.typing.centroid,
            r.typing_release.centroid,
            r.typing.attack_centroid,
            r.typing.crest_db
        );
    }
    println!(
        "\nLK = K-weighted (BS.1770) level over 100 ms from onset; RMS60, centroid = first 60 ms;\n\
         attack = centroid of the first 12 ms; HF>4k = share of the first 5 ms above 4 kHz;\n\
         crest = peak / RMS60. Durations are after tail trimming."
    );
}
